// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caixhcxhndvysrpklkwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaXhoY3hobmR2eXNycGtsa3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDI1ODksImV4cCI6MjA2MDAxODU4OX0.nePXPjdYsCEY5RT0yvM-5I3r7HSWJ60CIelrWia2mJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);